### ISSUE TITLE
Add Craft of Exile support

### ISSUE THREAD

**Issue by czarandy** [flbraun/poe-palette#40]
It would be amazing to add Craft of Exile support. So I could type a base like "Boots" and it would open it in craft of exile. (Or similarly for poedb).

**Comment by flbraun** [comment]
Good idea, but we won't get very far with it. CoE doesn't offer deeplinks for the emulator and simulator we can use as an entrypoint.

For the affix calculator we can enter for a specific base type (e.g. `Boots (Dex/Int`) though.
