### ISSUE TITLE
Integrate poe-antiquary.xyz

### ISSUE THREAD

**Issue by flbraun** [flbraun/poe-palette#43]
[PoE Antiquary](https://poe-antiquary.xyz/) hosts pricing information from past leagues and retains this data for way longer than poe.ninja does.

Suggested by u/SomeSortOfBird on [Reddit](https://www.reddit.com/r/pathofexile/comments/189twk9/introducing_poe_palette_a_command_palette_for/kbtvv1x/).

**Comment by flbraun** [comment]
Thanks a ton! That'll save me a lot of headache.

Do you enforce any kind of rate limit on that api? poe-palette currently updates its search index once per day, meaning I'd hit your API once a day for every item I fetched from the wiki (currently ~3800).

**Comment by CBrach** [comment]
I don't think that there is any limit in place. The request runs against a fully index supported database query, so I wouldn't expect any performance issues either. 

Feel free to give it a try and let me know if there are any issues!

**Comment by flbraun** [comment]
Hi @CBrach ! As you can see I finally got around to integrate Antiquary.

Your macro endpoint worked very well for me.

You can identify requests from the Palette data scraper by the [user agent](https://github.com/flbraun/poe-palette/blob/c39ebbbe729a839db829ea664c60faed950e94d0/data/utils.py#L23). Let me know if there is any problem.
